spring:
  redis:
    host: 62.234.138.175
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 5
        max-wait: 1000
        max-idle: 1
        min-idle: 2
    timeout: 5000
    password: 123456