#spring
spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5242880

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    # 默认不起用缓存
    cache: false
    servlet:
      content-type: text/html

  datasource:

    type: com.alibaba.druid.pool.DruidDataSource

    driver-class-name: com.mysql.cj.jdbc.Driver

    # 以下链接信息为默认, 会从其他配置文件替换
    url: jdbc:mysql://rm-wz95t7r1kxw72u800yo.mysql.rds.aliyuncs.com:3306/p2p?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=2&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: descendant_123

    # 配置获取连接等待超时的时间
    maxWait: 6000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    # 用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
    validationQuery: select 1
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    # 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有： 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
    # 配置监控统计拦截的 filters, 去掉后监控界面 sql 无法统计, 'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #initialize: true
    #continue-on-error: true

  aop:
    # 启动 aop 切面编程
    proxy-target-class: true
    # http 编码
  http:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
      enabled: true
  transaction:
    rollback-on-commit-failure: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml


# mybatis 分页管理器
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true


pictureCodeWidth: 140
pictureCodeHeight: 40
pictureCodeCount: 5
pictureCodeLineCount: 50